# Generated by Django 2.0.7 on 2018-07-17 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukutamu',
            name='gambar',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
