# Generated by Django 2.0.7 on 2018-07-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bukutamu_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukutamu',
            name='gambar',
            field=models.TextField(default=''),
        ),
    ]
