# Generated by Django 2.0.7 on 2018-07-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180718_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukutamu',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
