# Generated by Django 2.0.7 on 2018-07-19 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bukutamu_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukutamu',
            name='bio',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
